export default {
    HOME_NAVIGATOR: 'homeNavigator',
    HOME_SCREEN: 'homeScreen',
    CART_NAVIGATOR: 'cartsNavigator',
    CART_SCREEN: 'cartsScreen',
    ORDER_SCREEN: 'ordersScreen',
    CHECKOUT_SCREEN: 'checkoutScreen',
    ADDRESS_SCREEN: 'addressScreen',
    ITEM_DETAILS_SCREEN: 'itemDetailsScreen',
    PAYMENT_SCREEN: 'paymentScreen',
    SIGN_SCREEN: 'signInScreen',
    OTP_SCREEN: 'otpScreen',
    APP_NAVIGATION: 'appNavigation',
    USER_PROFILE_INPUT_SCREEN: 'userProfileInputScreen',
};